image: python:3.11-alpine

stages:
  # - test
  - deploy_docs

# test:
#   stage: test
#   image: julia:1.11
#   script:
#     - apt-get update && apt-get install -y lcov
#     - julia --project=. -e 'using Pkg; Pkg.instantiate()'
#     - julia scripts/generate_coverage_manual.jl
#     - genhtml lcov.info --output-directory coverage_html
#   artifacts:
#     paths:
#       - coverage_html
#       - lcov.info

pages:
  stage: deploy_docs
  script:
    - pip install -r docs/requirements.txt
    - zensical build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
