site_name: DES Julia 6G
site_description: Julia-based Discrete Event Simulator for evaluating scalability of 5G Networks and beyond
site_url: https://software-networks.org/des_julia_6g_rupa/
site_dir: public
copyright: Copyright &copy; 2025 Fundacio i2CAT

nav:
  - Summary: index.md
  - Quickstart: quickstart.md
  - Country-Specific Datasets:
      - Getting Data Ready: agents/getting-data-ready.md
      - Countries:
          - Spain: agents/countries/spain.md
          - USA: agents/countries/usa.md
  - The Simulator:
      - How Simulator Works: simulation-details/how-simulator-works.md
      - Simulation Configuration: simulation-details/simulation-configuration.md
      - UPF Placement Strategy: simulation-details/k-means.md
      - Mobility Models: simulation-details/mobility-models.md
  - Scenarios:
      - Single-Tier Architecture:
          - scenarios/single_tier_architecture/setup.md
          - scenarios/single_tier_architecture/analysis.md
      - Two-Tier Architecture:
          - scenarios/two_tier_architecture/setup.md
          - scenarios/two_tier_architecture/analysis.md
      - Mobility:
          - scenarios/mobility/setup.md
          - scenarios/mobility/analysis.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - tables
  - md_in_html

plugins:
  - search
  - build_plantuml:
      render: "server"
      server: "http://www.plantuml.com/plantuml"
      disable_ssl_certificate_validation: true
      output_format: "svg"
      allow_multiple_roots: false
      diagram_root: "docs/plantuml-diagrams"
      output_folder: "out"
      input_folder: "../../src"
      input_extensions: ""
